### ISSUE TITLE
Crypto dependancies refactor

### ISSUE THREAD

**Issue by chunningham** [decentralized-identity/keriox#15]
Currently this crate relies upon URSA, however this will not provide support for all required crypto types in future. This task represents refactoring core crypto usage to use the [RustCrypto](https://github.com/RustCrypto) family of cryptography traits and implementations.

**Comment by blelump** [comment]
Basically #16 may be related to this one. As we've started with rotation and touched `ursa` key pair generation for given seed, it appeared that the keypair values are different than for those given from libNaCl (keripy basically). So in the end my understanding is that: any message signed with a secret key from libNaCl that would be later verified with a public key from keypair generated by some Rust impl would fail. Not sure my understanding is right here, but basically I'd expect the keypairs are always the same for given seed. So the direction would be to a libNaCl-compliant lib.

**Comment by chunningham** [comment]
you're right, the key pair generation from seed should (but may not) be consistant with keripy, however this should not affect the verifiability of the signatures themselves, just the outcome of programs which start with a seed and go through key derivation and then signing/verification (the key pair will be "wrong" as you point out). Ursa actually uses a libsodium binding under the hood if used in non-portable mode (which should be compatible with portable mode, the tests are the same for both), so I wonder what is causing this

**Comment by blelump** [comment]
Hi Charles,

as you've pointed out, it should not affect the overall behavior. Ursa internally uses https://docs.rs/crate/curve25519-dalek/2.1.0 and apparently it seems this is 100% Rust impl. We've also tried https://github.com/maidsafe/rust_sodium and it gave the same results as Python (as it natively uses libsodium).

Overall RustCrypto is more like a collection of facades so it opens a discussion to go/no go with libsodium behind them or some native implementation (or how they call them, [providers](https://docs.rs/ed25519/1.0.2/ed25519/index.html#available-ed25519-providers)). Here I am not sure about portability if choosing the former approach.

**Comment by fimbault** [comment]
https://github.com/project-oak/tink-rust seems to implement a collection of facades

**Comment by SmithSamuelM** [comment]
One of the reasons the Python implementation uses LibSodium is that it is a universally supported library across multiple languages with broad adoption by many systems.  But it has some tweaks in its implementation that may look long in the tooth.  I am not sure that this matters as long as the same private/public key pair is used for a given siganture. It does make it harder as is pointed out above to create test vectors starting from a random salt. There is also some terminology drift. In libsodium and other papers by Daniel Bernstein he used the term seed to mean private key and salt to mean the random number from which the private key is generated.  Because a private key may be a random number its valid to call it a seed. 

So I am not sure how to interpret the problem described above because I am not sure how you are using the terms seed and private key when you say the private key is derived from the seed.   LibSodium provides library functions that generate the public from a private key ``` pysodium.crypto_sign_seed_keypair(sigseed)```  where sigseed is the private key.  So it seems like what is happening is that Ursa uses a different representation for the sigseed, private key that generates the same public key?   Or is it something else?  I am concerned that key management libraries might have problems porting key stores if there is not an interoperable representation for the private keys for each of the signature types supported by Keri.  Is that something we need to discuss?

**Comment by SmithSamuelM** [comment]
Here is the relevant python code that shows how LibSodium is representing key pairs.  

```python
verkey, sigkey = pysodium.crypto_sign_seed_keypair(sigseed)
    assert len(verkey) == 32
    assert len(sigkey) == 64
    #  sigkey is seed and verkey concatenated. Libsodium does this as an optimization
    #  because the signing scheme needs both the private key (seed) and the public key so
    #  instead of recomputing the public key each time from the secret key it requires
    #  the public key as an input of and instead of two separate inputs, one for the
    #  secret key and one for the public key, it uses a concatenated form.
    #  Essentially crypto_sign_seed_keypair and crypto_sign_keypair return redundant
    #  information in the duple (verkey, sigkey) because sigkey includes verkey
    #  so one could just store sigkey and extract verkey or sigseed when needed
    #  or one could just store verkey and sigseed and reconstruct sigkey when needed.
    #  crypto_sign_detached requires sigkey (sigseed + verkey)
    #  crypto_sign_verify_detached reqires verkey only
    #  https://crypto.stackexchange.com/questions/54353/why-are-nacl-secret-keys-64-bytes-for-signing-but-32-bytes-for-box
    assert sigseed == sigkey[:32]
    assert verkey == sigkey[32:]
    assert sigkey == sigseed + verkey
```
So although libsodium is using the term "seed" in its parameter list for  the argument to ```pysodium.crypto_sign_seed_keypair``` it is indeed the private key for the resultant verkey or public key. No other representation is exposed.  So I suspect that Ursa is not generating the public key that same way that ```pysodium.crypto_sign_seed_keypair``` does from the same private key. But the signatures would not verify for a given public key if it were not true that under the hood there is a one-to-one equivalence and therefore a way to convert or map from the libsodium private key (seed) to the Ursa private key (seed). It seems that for the sake of interoperability we need to find out what that mapping is and create a function in Ursa to make the equivalence. Then we have interoperable test vectors and interoperable key stores.

**Comment by fimbault** [comment]
I guess this could be due to https://github.com/dalek-cryptography/ed25519-dalek#a-note-on-signature-malleability

**Comment by SmithSamuelM** [comment]
It is discussed in more detail here 
https://github.com/dalek-cryptography/ed25519-dalek/issues/20

And the maintainer of libsodium made a comment that it fixed it but did not elaborate. 

> The check was re-added shortly after (ge25519_is_canonical()), and RFC 8032 that stands as the current specification, requires it.

There may be an issue but Libsodium and the Ed25519/RFC 8032 are standards. Breaking those standards is problematic unless there is a known exploit not a hypothetical exploit.  

IMHO the correct way to deal with this in KERI is that if someone wants to use ed25519-Dalek instead of ed25519/RFC 8032 then we give it a unique derivation code in KERI so that we have totally interoperable usage.

**Comment by fimbault** [comment]
Well, the most elaborate discussions about this are from [zcash] (https://hdevalence.ca/blog/2020-10-04-its-25519am) and [Facebook](https://research.fb.com/publications/taming-the-many-eddsas/).
I wouldn't agree that sodium is per definition the valid implementation, but indeed compatibility between implementation is important.

**Comment by blelump** [comment]
> IMHO the correct way to deal with this in KERI is that if someone wants to use ed25519-Dalek instead of ed25519/RFC-8032 then we give Ed25519-Dalek a unique derivation code in KERI so that we have totally interoperable usage with the rest of the world.

we could definitely consider that. 

The main reason not to use LibSodium implementation in KERIOX is WebAssembly. Currently KERIOX uses URSA with FFI layers to NaCl, but PR https://github.com/decentralized-identity/keriox/pull/68 addresses exactly this issue main concern, so to switch to different crypto family, as Charles pointed out. The Ed25519 implementation https://github.com/RustCrypto/signatures/tree/master/ed25519 is RFC8032 compliant so the interop should remain compliant.

**Comment by 35359595** [comment]
did a quick test `libsodium <--> ed25519-dalek` sign + verify = everything works.
@edytapawlak also tested key generation from same seed - no issues and keys are matching.

looks like we're good to go.

<img width="1330" alt="Screen Shot 2021-05-06 at 4 27 25 PM" src="https://user-images.githubusercontent.com/13215338/117316195-a875a680-ae88-11eb-8563-c7a086fb31e6.png">

**Comment by 35359595** [comment]
the only thing libsodium does differently is that it's secret key struct is 64 bytes concatenation of actual secret + public keys.
in depth description here: https://crypto.stackexchange.com/questions/54353/why-are-nacl-secret-keys-64-bytes-for-signing-but-32-bytes-for-box/54367#54367

so it's just a matter of consumers to provide proper size of the secret key.
